name: "Deploy Now: Execute Build"

on:
  workflow_call:
    inputs:
      site-url:
        required: true
        type: string
      branch-id:
        required: true
        type: string

env:
  DEPLOYMENT_FOLDER: build

jobs:
  build-project:
    name: Build CMT_V1
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du dépôt
        uses: actions/checkout@v3
        with:
          submodules: "recursive"

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: v22.x

      - name: Build des fichiers
        env:
          CI: false
          SITE_URL: ${{ inputs.site-url }}
        run: |
          npm ci
          npm run build

      - name: Stocker les fichiers pour le déploiement
        uses: ionos-deploy-now/artifact-action@v1
        with:
          api-key: ${{ secrets.IONOS_API_KEY }}
          service-host: api-eu.ionos.space
          project-id: ${{ secrets.IONOS_PROJECT_ID }}
          branch-id: ${{ inputs.branch-id }}
          version: ${{ github.sha }}
          folder: ${{ env.DEPLOYMENT_FOLDER }}
          config-file: .deploy-now/CMT_V1/config.yaml
          action: upload
