name: "Deploy Now: Execute Build"

on:
  push:
    branches:
      - master # ✅ Déclenche le build uniquement sur master
  workflow_call:
    inputs:
      site-url:
        required: true
        type: string
      branch-id:
        required: true
        type: string

env:
  DEPLOYMENT_FOLDER: build

jobs:
  build-project:
    name: Build CMT_V1
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du dépôt
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # ✅ Vérifie que cette version est bien supportée

      - name: Installer les dépendances
        run: npm ci

      - name: Lancer le build
        run: npm run build

      - name: Stocker les fichiers pour le déploiement
        uses: ionos-deploy-now/artifact-action@v1
        with:
          api-key: ${{ secrets.IONOS_API_KEY }}
          service-host: api-eu.ionos.space
          project-id: ${{ secrets.IONOS_PROJECT_ID }}
          branch-id: ${{ inputs.branch-id || github.ref_name }}
          version: ${{ github.sha }}
          folder: ${{ env.DEPLOYMENT_FOLDER }}
          config-file: .deploy-now/CMT_V1/config.yaml
          action: upload
