name: "Deploy Now: Deploy to IONOS"

on:
  push:
    branches:
      - master

env:
  PROJECT_ID: ${{ secrets.IONOS_PROJECT_ID || 'MISSING_PROJECT_ID' }}
  IONOS_API_KEY: ${{ secrets.IONOS_API_KEY }}

jobs:
  deploy-to-ionos:
    runs-on: ubuntu-latest
    steps:
      - name: Vérifier le contexte et les variables
        run: |
          echo "Branche actuelle : ${{ github.ref_name }}"
          echo "Project ID : '${{ env.PROJECT_ID }}'"
          echo "API Key définie : '${{ env.IONOS_API_KEY }}'"

      - name: Vérifier que `PROJECT_ID` est bien défini
        run: |
          if [ "${{ env.PROJECT_ID }}" == "MISSING_PROJECT_ID" ]; then
            echo "Erreur : Aucun project-id trouvé. Vérifie que `IONOS_PROJECT_ID` est bien défini dans GitHub Secrets."
            exit 1
          fi

      - name: Récupérer le code du dépôt
        uses: actions/checkout@v3

      - name: Déploiement sur IONOS
        uses: ionos-deploy-now/deploy-to-ionos-action@v2
        with:
          api-key: ${{ env.IONOS_API_KEY }}
          service-host: api-eu.ionos.space
          project-id: ${{ env.PROJECT_ID }}
          branch-id: ${{ github.ref_name }}
