name: "Deploy Now: Deploy to IONOS"

on:
  push:
    branches:
      - master

env:
  PROJECT_ID: ${{ secrets.IONOS_PROJECT_ID }}
  IONOS_API_KEY: ${{ secrets.IONOS_API_KEY }}

jobs:
  deploy-to-ionos:
    runs-on: ubuntu-latest
    steps:
      - name: Vérifier le contexte
        run: |
          echo "Branche actuelle : ${{ github.ref_name }}"
          echo "Project ID : ${{ env.PROJECT_ID }}"

      - name: Déploiement sur IONOS
        uses: ionos-deploy-now/deploy-to-ionos-action@v2
        with:
          api-key: ${{ env.IONOS_API_KEY }}
          service-host: api-eu.ionos.space
          project-id: ${{ env.PROJECT_ID }}
          branch-id: ${{ github.ref_name }}
